token: find your token in cookie
group_id: your group id
invalids:
  - student_id: plagiarist
    problem_id: plagiarized problem
  - student_id: another plagiarist
    problem_id: another plagiarized problem
students:
  - student ids
  - from
  - e3
problems:
  - id: problem id
    deadline: deadline in this format (2019-10-02 12:34:56)
  - id: problem id
    deadline: deadline
    ips:
      - a valid ip
      - another valid ip
